**Shortcuts**

- Above - Esc, A
- Below - Esc, B
- Markdown - Esc, M
- Code - Esc, Y
- Delete - Esc, DD
- Esc - Z

### Numpy 

**Installation** 

```pip install numpy```

In [2]:
"Hello"  

'Hello'

In [3]:
!pip install numpy

You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [8]:
import numpy as np

In [15]:
l = [1,2,3]
a = np.array(l)
print(a)
print(type(a))
print(l)
print(type(l))

[1 2 3]
<class 'numpy.ndarray'>
[1, 2, 3]
<class 'list'>


In [18]:
5*(a + 1)

array([10, 15, 20])

In [19]:
arr = np.array([
                [1,2,3],
                [4,5,6]
               ])
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
arr.shape
print(type(arr))
print(type(arr.shape))

<class 'numpy.ndarray'>
<class 'tuple'>


In [24]:
z = np.zeros((5,3),dtype='int')
z[1:3, 0:2]  = 4
print(z)

[[0 0 0]
 [4 4 0]
 [4 4 0]
 [0 0 0]
 [0 0 0]]


In [25]:
z.T

array([[0, 4, 4, 0, 0],
       [0, 4, 4, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.dot(z,z.T)

array([[ 0,  0,  0,  0,  0],
       [ 0, 32, 32,  0,  0],
       [ 0, 32, 32,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [31]:
z = z + 1 #Broadcasting
print(z)

[[3 3 3]
 [7 7 3]
 [7 7 3]
 [3 3 3]
 [3 3 3]]


In [34]:
z[0,2] #Acess i,j th element

3

In [35]:
a = np.array([1,2,3,4,5])
print(z+a)

[[4 5 6]
 [8 9 6]
 [8 9 6]
 [4 5 6]
 [4 5 6]]


In [36]:
print(a.shape)

(3,)


In [41]:
a2= np.array([[1],[2],[3],[4],[5]])
print(a2.shape)
print(a2)

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [43]:
print(z)
print(z+a2)

[[3 3 3]
 [7 7 3]
 [7 7 3]
 [3 3 3]
 [3 3 3]]
[[ 4  4  4]
 [ 9  9  5]
 [10 10  6]
 [ 7  7  7]
 [ 8  8  8]]


In [48]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [49]:
np.linalg.det(a)

1.0

In [50]:
np.linalg.pinv(a)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
a = np.array([[1,2],[3,4]])
ainv = np.linalg.pinv(a)
print(a)
print(ainv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [62]:
np.round(np.dot(a,ainv))

array([[ 1., -0.],
       [ 0.,  1.]])

In [60]:
np.round(np.dot(a,np.linalg.inv(a)))

array([[1., 0.],
       [0., 1.]])

In [67]:
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [68]:
a**0.5

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [74]:
v = np.array([[1,2,3]])
print(v)
print(v.shape)

[[1 2 3]]
(1, 3)


In [75]:
m=  np.dot(v,v.T)
m[0][0]

14

In [76]:
np.dot(v.T,v) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [83]:
a = np.array([1,2,3])
print(a.shape)
print(a.T)
print(a.T.shape)

(3,)
[1 2 3]
(3,)


In [80]:
np.dot(a,a.T) #Dot Product of Vectors

14

In [82]:
a = a.reshape((3,1))
print(a)
np.dot(a.T,a) #Dot Product of Matrices

[[1]
 [2]
 [3]]


array([[14]])

In [97]:
a = np.array([[1,2,3,4,5,4],
             [4,5,6,2,3,4]])

b = a.reshape((-1,2))
print(b)

[[1 2]
 [3 4]
 [5 4]
 [4 5]
 [6 2]
 [3 4]]


In [99]:
np.random.randint(10,20,5)

array([13, 10, 18, 18, 11])

In [100]:
np.random.randint(10,20,(3,4))

array([[15, 17, 10, 15],
       [16, 15, 11, 10],
       [18, 11, 16, 12]])

In [101]:
np.random.randint(10,20,(3,4,2))

array([[[13, 16],
        [14, 10],
        [18, 14],
        [17, 15]],

       [[11, 18],
        [14, 12],
        [14, 14],
        [10, 17]],

       [[11, 12],
        [16, 15],
        [16, 18],
        [11, 12]]])